sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.7
script: bundle exec rspec
bundler_args: --without development
notifications:
  email: false
before_script:
  - "psql -c 'create database cobot_fb_test;' -U postgres"
  - "RACK_ENV=test bundle exec rake ar:migrate"
addons:
  postgresql: "9.4"
branches:
  only:
  - master

