sudo: false
dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.4.9
script: bundle exec rspec
bundler_args: --without development
notifications:
  email: false
before_script:
  - "psql -c 'create database cobot_fb_test;' -U postgres"
  - "RACK_ENV=test bundle exec rake ar:migrate"
addons:
  postgresql: "9.6"
branches:
  only:
    - master
